version: "3.9"
services:
  db:
    image: mysql
    build:
      context: ./docker
      dockerfile: mysql.Dockerfile
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_password
      MYSQL_DATABASE: app_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user_pass
    ports:
      - "6033:3306"
    volumes:
      - ./mysql:/home/work
  jupyter:
    image: jupyter
    build:
      context: ./docker
      dockerfile: jupyter.Dockerfile
    links:
      - db
    volumes:
      - ./work:/home/jovyan/work
    ports:
      - 8888:8888
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80